---
title: "Publications"
output: html_document
---
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-140504233-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-140504233-1');
</script>

#### 2019
##### **Beita-Jiménez, A.**, Alvarado, J.J., Mena, S. &  Guzmán, A.G. (2019). [Benefits of protection on reef fish assemblages in a human impacted region in Costa Rica.](files/Beitaetal2019_FishNorthPacific_OceansCoastalMngmt.pdf) Oceans and Coastal Management, 169, 165-170.

##### Auster, P.J., Cortés, J., Alvarado J.J., & **Beita-Jiménez, A**. (2019). [Coordinated hunting behaviors of mixed species groups of piscivores and associated species at Isla del Coco National Park (Eastern Tropical Pacific).](http://www.scielo.br/pdf/ni/v17n1/1982-0224-ni-17-01-e180165.pdf) Neotropical Ichthyology, 17, (1), e180165.

#### 2018
##### Alvarado, J. J., **Beita-Jiménez, A.**, Mena, S., Fernández-García, F., Cortés, J., Sánchez-Noriega, C., Jiménez, C. & Guzmán, A. G. (2018). [When conservation can’t keep up with development ́s pace: Health status of coral ecosystems in the North Pacific of Costa Rica.](files/Alvaradoetal2018-Cuando la conservacion.pdf) Revista de Biología Tropical, 66(Suppl. 1), S280-S308. (In Spanish with English abstract) 

#### 2016
##### **Beita-Jiménez, A.** & Alvarado, J.J. (2016). [Unusual coloration in the yellow tail damselfish Stegastes arcifrons (Actinopterygii: Pomacentridae) at Isla del Coco National Park, Costa Rica.](files/Beita&Alvarado2016.pdf) Revista de Biología Tropical. 64(Suppl. 1), 197-199.

##### Alvarado, J. J., **Beita-Jiménez, A.**, Mena, S., Fernández-García, F., Guzmán, A. G., & Cortés, J. (2016). [Coral reefs of Isla del Coco National Park, Costa Rica: structure and comparison (1987-2014).](files/Alvaradoetal2016-isladelcoco.pdf) Revista de Biología Tropical, 61(Suppl. 1), 153-175. (In Spanish with English abstract) 


#### 2015
##### Alvarado, J.J, **Beita-Jiménez, A.**, Mena, S., Fernández C. &  Guzmán A.G.(2015). [Osa Conservation Area (Costa Rica) coral ecosystems: structure and conservation needs.](files/Alvaradoetal2015-osa.pdf) Revista de Biología Tropical. 63 (Suppl. 1), 219-259. (In Spanish with English abstract)

#### 2014
##### Villalobos-Rojas, F., Herrera-Correal, J., Garita-Alvarado, C., Clarke T. & **Beita-Jiménez A.** (2014). [Economic activities that depend on ichthyofauna in the North Pacific of Costa Rica.](files/Villalobos-Rojasetal2014.pdf) Revista de Biología Tropical. 62 (Suppl. 4), 119-138. (In Spanish with English abstract)

##### Look at my profiles in [Scholar Google](https://scholar.google.com/citations?user=nJn08rgAAAAJ&hl=en) or [Research Gate](https://www.researchgate.net/profile/Andres_Beita-Jimenez) for more details. 


